version: '3.8'

services:
  todo-api:
    container_name: todo-api 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - logs:/usr/src/app/logs
    ports:
      - "5454:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}

  m01:
    container_name: m01
    image: mongo:latest
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  logs:
    driver: local
  mongodb_data_container:
    driver: local