version: '3.8'

services:
  todo-api:
    container_name: todo-api 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - logs:/usr/src/app/logs
    ports:
      - "5454:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}

volumes:
  logs:
    driver: local